### ISSUE TITLE
cross-domain issue

### ISSUE THREAD

**Issue by opeeters** [52North/sensorweby#20]
Selecting a time series originating from endpoints served from a differtent domain than the shiny server instance triggers an error with this error message:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/
```
The (openair) diagram is not drawn...
See e.g. any of the examples here: http://shiny.irceline.be/examples
Select either data from the RIVM or UoL entpoint.

**Comment by opeeters** [comment]
The message:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/
also appears when no time series are selected, so it might after all not be related. It is in anycase impossible to draw graphs correctly of data coming from a foreign endpoint it seems, at least from an app hosted by shiny server.

**Comment by autermann** [comment]
> Selecting a time series originating from enpoints served from a differtent domain than the shiny server instance triggers an error with this error message:
> 
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/

That's not an error, that's a warning. And it's not caused by `sensorweby` but by the client [itself](https://github.com/52North/sensorweby/blob/master/inst/www/jsc/js/jsc-1.0.0-SNAPSHOT.js#L1337).

> It is in anycase impossible to draw graphs correctly of data coming from a foreign endpoint it seems, at least from an app hosted by shiny server.

Well, it's definitely not an cross-domain issue, as the requests are issued from the server side. Also `shiny.irceline.be`, `sosrest.irceline.be`, `geostatistics.demo.52north.org` and `sensorweb.demo.52north.org` are all different domain names, but everything works fine.

So the problem seems to be something different...

**Comment by nuest** [comment]
I concur this is not the reason of the error.

@autermann could you point Olav to the documentation about configuring logging, please? Maybe that helps us to see what goes wrong with the RIVM and UoL endpoints. IRCELINE endpoint works fine in my brief tests.

**Comment by nuest** [comment]
So the issues can be reproduced when using **more than one timeseries API endpoint**.

**Comment by opeeters** [comment]
some more log output..
on a local install:

library(devtools)
devtools::install_github("52North/sensorweb4R")
## to have the endpoint for the example below:
devtools::install_github("irceline/sensorweby")
sensorweby::runExample("timePlot")

When you select timeseries from the default IRCEL - CELINE endpoint, all is well:

[INFO] [2015-03-27 14:33:12] [sensorweby.::] Parsing timeseries:
	
Warning in gsub("~f", the.function, message, fixed = TRUE) :
  argument 'replacement' has length > 1 and only the first element will be used
[INFO] [2015-03-27 14:33:22] [sensorweby.::] Parsing timeseries:
	http://sosrest.irceline.be/api/v1/timeseries/ts_79d29d23c0ee4a590a5cc4b8e3fbcdf
	http://sosrest.irceline.be/api/v1/timeseries/ts_9c59da94a1684093dcbc046c5452347f
Warning in checkPrep(mydata, vars, type, remove.calm = FALSE) :
  Detected data with Daylight Saving Time, converting to UTC/GMT
Warning in checkPrep(mydata, vars, type, remove.calm = FALSE) :
  Detected data with Daylight Saving Time, converting to UTC/GMT
Warning in gsub("~f", the.function, message, fixed = TRUE) :
  argument 'replacement' has length > 1 and only the first element will be used



When you select timeseries from the RIVM/Geonovum endpoint, this happens:

[INFO] [2015-03-27 14:33:36] [sensorweby.::] Parsing timeseries:
	
Warning in gsub("~f", the.function, message, fixed = TRUE) :
  argument 'replacement' has length > 1 and only the first element will be used
[INFO] [2015-03-27 14:33:51] [sensorweby.::] Parsing timeseries:
	http://sensors.geonovum.nl/sos/api/v1/timeseries/37
	http://sensors.geonovum.nl/sos/api/v1/timeseries/89
Can't find the variable(s) 37 89 
Error in checkPrep(mydata, vars, type, remove.calm = FALSE) : 
Can't find the variable(s) 37 89 
Error in checkPrep(mydata, vars, type, remove.calm = FALSE) : 

The timeseries are correctly displayed in the chart-view of the js-client

I wil now check this on a shiny server, but this also is an issue on a local machine..

**Comment by autermann** [comment]
Sounds like that the Timeseries IDs are converted to `numeric`s in R and are therefore handled differently. All endpoints I tested before used identifiers like `ts_...` that were handled as `characters`.

**Comment by opeeters** [comment]
:-) this could well be it..

**Comment by autermann** [comment]
With a small change the `timePlot` example is now compatible with numeric IDs and the RIVM endpoint (see https://github.com/52North/sensorweb4R/pull/33).

**Comment by autermann** [comment]
Wrong pull request... I meant this one: https://github.com/52North/sensorweby/pull/23
